# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "2.7", "3.11" ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      if: matrix.python-version == '3.11'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python 2
      if: matrix.python-version == '2.7'
      run: |
        sudo apt update
        sudo apt install python2 python-pip
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
        printf '1\n' | sudo update-alternatives --config python
        cd /usr/bin
        sudo ln -s /usr/bin/pip2 ./pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -e .

    - name: Tests
      run: |
       mamba
